[tool.black]
line-length = 100
target-version = ["py38"]

[tool.isort]
src_paths = [
    "tools",
    "zulip",
    "zulip/integrations/zephyr",
    "zulip_bots",
    "zulip_botserver",
]
profile = "black"
line_length = 100

[tool.mypy]
mypy_path = [
    "$MYPY_CONFIG_FILE_DIR/stubs",
    "$MYPY_CONFIG_FILE_DIR/tools",
    "$MYPY_CONFIG_FILE_DIR/zulip",
    "$MYPY_CONFIG_FILE_DIR/zulip/integrations/bridge_between_zulips",
    "$MYPY_CONFIG_FILE_DIR/zulip/integrations/bridge_with_irc",
    "$MYPY_CONFIG_FILE_DIR/zulip/integrations/bridge_with_slack",
    "$MYPY_CONFIG_FILE_DIR/zulip/integrations/codebase",
    "$MYPY_CONFIG_FILE_DIR/zulip/integrations/git",
    "$MYPY_CONFIG_FILE_DIR/zulip/integrations/openshift",
    "$MYPY_CONFIG_FILE_DIR/zulip/integrations/perforce",
    "$MYPY_CONFIG_FILE_DIR/zulip/integrations/svn",
    "$MYPY_CONFIG_FILE_DIR/zulip/integrations/trac",
    "$MYPY_CONFIG_FILE_DIR/zulip/integrations/zephyr",
    "$MYPY_CONFIG_FILE_DIR/zulip_bots",
    "$MYPY_CONFIG_FILE_DIR/zulip_botserver",
]
explicit_package_bases = true

scripts_are_modules = true
show_traceback = true

# Enable strict mode, with some exceptions.
strict = true
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_untyped_decorators = false
warn_return_any = false

# Enable optional errors.
enable_error_code = [
    "redundant-self",
    "redundant-expr",
    "truthy-bool",
    "truthy-iterable",
    "ignore-without-code",
    "unused-awaitable",
    "explicit-override",
]

# Other options.
warn_unreachable = true

[[tool.mypy.overrides]]
module = [
    "apiai.*",
    "feedparser.*",
    "gitlint.*",
    "googleapiclient.*",
    "irc.*",
    "markdownify.*",
    "mercurial.*",
    "nio.*",
    "oauth2client.*",
    "pysvn.*",
    "scripts.*",
    "setuptools.*",
    "simple_salesforce.*",
    "slack_sdk.*",
    "sleekxmpp.*",
    "trac.*",
    "twitter.*",
    "wit.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "git_p4",
]
ignore_errors = true

[tool.pytest.ini_options]
pythonpath = [
    "zulip",
    "zulip_bots",
    "zulip_botserver",
]

[tool.ruff]
select = [
    "E", # style errors
    "F", # flakes
    "I", # import sorting
]
ignore = [
    "E402", # Module level import not at top of file
    "E501", # Line too long
    "E731", # Do not assign a `lambda` expression, use a `def`
]
src = [
    "tools",
    "zulip",
    "zulip/integrations/zephyr",
    "zulip_bots",
    "zulip_botserver",
]
target-version = "py38"
line-length = 100
